### ISSUE TITLE
lis25ba no example

### ISSUE THREAD

**Issue by ZimaBlue1996** [STMicroelectronics/lis25ba#1]
### lis25ba

lis25ba

### Describe the bug

lis25ba no example

**Comment by avisconti** [comment]
OK, I may add something. Is there an example of reading data enough or do you require other examples as well?

**Comment by ZimaBlue1996** [comment]
Thanks, I don't have special data, a general example will suffice

**Comment by ZimaBlue1996** [comment]
> OK, I may add something. Is there an example of reading data enough or do you require other examples as well?

Thanks, I don't have special data, a general example will suffice
